# tools/email_sender.py
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from config import FROM_EMAIL, TO_EMAIL, SMTP_PASSWORD
from datetime import datetime
import html

def build_html_digest(items_by_category):
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    html_parts = [f"<h2>Daily AI Digest — {now}</h2>"]
    # items_by_category is expected as dict: {domain: {category: [items]}}
    for domain, cats in items_by_category.items():
        html_parts.append(f"<h2>🌐 {html.escape(domain.title())}</h2>")
        for cat, items in cats.items():
            html_parts.append(f"<h3>{html.escape(cat)} ({len(items)})</h3><ul>")
            for it in items:
                title = html.escape(it.get("title") or "No title")
                url = html.escape(it.get("url") or "")
                summary = (it.get("summary") or "").replace("\n", "<br/>")
                html_parts.append(
                    f"<li><a href='{url}'>{title}</a>"
                    f"<div style='font-size:0.95em;color:#444'>{summary}</div></li><br/>"
                )
            html_parts.append("</ul>")
    html_parts.append("<hr><small>Generated by TechDigestAgent</small>")
    return "<html><body>" + "\n".join(html_parts) + "</body></html>"

def send_email_html(subject, html_body):
    if not (FROM_EMAIL and SMTP_PASSWORD and TO_EMAIL):
        print("Email config missing, skipping send. FROM/TO/PASS must be set.")
        return
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = FROM_EMAIL
    msg["To"] = TO_EMAIL
    part = MIMEText(html_body, "html")
    msg.attach(part)
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(FROM_EMAIL, SMTP_PASSWORD)
            server.sendmail(FROM_EMAIL, [TO_EMAIL], msg.as_string())
        print("Email sent.")
    except Exception as e:
        print("Email send failed:", e)
